-- ============================================================
-- Queen's Park Trust • Canal Watch Survey Schedule
-- FINAL LIVE SCHEMA
--
-- IMPORTANT:
-- This replaces the earlier prototype schema.
-- It separates secure administrator logins from volunteer records,
-- so volunteers DO NOT need a login or an email address.
--
-- Run this in Supabase SQL Editor.
-- It assumes the app tables are still empty.
-- ============================================================

-- Remove earlier trigger/function that tied every volunteer to auth.users.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.is_schedule_manager() cascade;

-- Remove the earlier app tables. This does NOT delete Supabase Auth users.
drop table if exists public.assignment_users cascade;
drop table if exists public.assignment_volunteers cascade;
drop table if exists public.assignment_teams cascade;
drop table if exists public.site_assignments cascade;
drop table if exists public.survey_round_sites cascade;
drop table if exists public.survey_rounds cascade;
drop table if exists public.survey_sites cascade;
drop table if exists public.project_team_members cascade;
drop table if exists public.project_teams cascade;
drop table if exists public.volunteers cascade;
drop table if exists public.profiles cascade;
drop table if exists public.admin_profiles cascade;

drop type if exists public.assignment_status cascade;

create type public.assignment_status as enum ('needed','covered','complete','cancelled');

-- Secure administrator accounts map to Supabase Authentication users.
create table public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Schedule manager',
  can_manage boolean not null default false,
  created_at timestamptz not null default now()
);

-- Volunteers are ordinary records and do NOT require Supabase Auth.
create table public.volunteers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.project_teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  coordinator_id bigint not null references public.volunteers(id),
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now()
);

create table public.project_team_members (
  team_id bigint not null references public.project_teams(id) on delete cascade,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  primary key (team_id, volunteer_id)
);

create table public.survey_sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  address text null,
  latitude double precision null check (latitude between -90 and 90),
  longitude double precision null check (longitude between -180 and 180),
  three_word_location text null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (
    (latitude is null and longitude is null)
    or
    (latitude is not null and longitude is not null)
  )
);

create table public.survey_rounds (
  id bigint generated by default as identity primary key,
  name text not null,
  survey_date date not null,
  status text not null default 'planned',
  recurrence text not null default 'none'
    check (recurrence in ('none','weekly','fortnightly','monthly','custom_days')),
  recurrence_interval integer not null default 1 check (recurrence_interval >= 1),
  auto_repeat boolean not null default false,
  parent_round_id bigint null references public.survey_rounds(id),
  created_at timestamptz not null default now()
);

create table public.survey_round_sites (
  survey_round_id bigint not null references public.survey_rounds(id) on delete cascade,
  survey_site_id bigint not null references public.survey_sites(id),
  primary key (survey_round_id, survey_site_id)
);

create table public.site_assignments (
  id bigint generated by default as identity primary key,
  survey_round_id bigint not null references public.survey_rounds(id) on delete cascade,
  survey_site_id bigint not null references public.survey_sites(id),
  status public.assignment_status not null default 'needed',
  notes text,
  unique (survey_round_id, survey_site_id)
);

create table public.assignment_teams (
  assignment_id bigint not null references public.site_assignments(id) on delete cascade,
  team_id bigint not null references public.project_teams(id),
  primary key (assignment_id, team_id)
);

create table public.assignment_volunteers (
  assignment_id bigint not null references public.site_assignments(id) on delete cascade,
  volunteer_id bigint not null references public.volunteers(id),
  primary key (assignment_id, volunteer_id)
);

-- Create an admin profile automatically when a Supabase Auth user is created.
create or replace function public.handle_new_admin_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.admin_profiles (id, display_name, can_manage)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      split_part(new.email, '@', 1),
      'Schedule manager'
    ),
    false
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_admin_user();

-- Backfill an admin profile for any Auth user you already created.
insert into public.admin_profiles (id, display_name, can_manage)
select
  id,
  coalesce(raw_user_meta_data ->> 'display_name', split_part(email,'@',1), 'Schedule manager'),
  false
from auth.users
on conflict (id) do nothing;

create or replace function public.is_schedule_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles
    where id = auth.uid()
      and can_manage = true
  );
$$;

-- RLS
alter table public.admin_profiles enable row level security;
alter table public.volunteers enable row level security;
alter table public.project_teams enable row level security;
alter table public.project_team_members enable row level security;
alter table public.survey_sites enable row level security;
alter table public.survey_rounds enable row level security;
alter table public.survey_round_sites enable row level security;
alter table public.site_assignments enable row level security;
alter table public.assignment_teams enable row level security;
alter table public.assignment_volunteers enable row level security;

grant usage on schema public to anon, authenticated;
grant execute on function public.is_schedule_manager() to authenticated;

-- Public schedule data.
grant select (id,name,active) on public.volunteers to anon;
grant select on public.project_teams, public.survey_sites, public.survey_rounds,
  public.survey_round_sites, public.site_assignments,
  public.assignment_teams, public.assignment_volunteers to anon;

-- Authenticated managers need full app access.
grant select, insert, update, delete on public.volunteers, public.project_teams,
  public.project_team_members, public.survey_sites, public.survey_rounds,
  public.survey_round_sites, public.site_assignments,
  public.assignment_teams, public.assignment_volunteers to authenticated;
grant select on public.admin_profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Public policies
create policy "Public read active volunteers"
on public.volunteers for select to anon
using (active = true);

create policy "Authenticated read volunteers"
on public.volunteers for select to authenticated
using (public.is_schedule_manager());

create policy "Public read active teams"
on public.project_teams for select to anon
using (active = true);

create policy "Authenticated read teams"
on public.project_teams for select to authenticated
using (public.is_schedule_manager());

create policy "Public read active sites"
on public.survey_sites for select to anon
using (active = true);

create policy "Authenticated read sites"
on public.survey_sites for select to authenticated
using (public.is_schedule_manager());

create policy "Public read active rounds"
on public.survey_rounds for select to anon
using (status <> 'inactive');

create policy "Authenticated read rounds"
on public.survey_rounds for select to authenticated
using (public.is_schedule_manager());

create policy "Public read round sites"
on public.survey_round_sites for select to anon
using (true);

create policy "Authenticated read round sites"
on public.survey_round_sites for select to authenticated
using (public.is_schedule_manager());

create policy "Public read assignments"
on public.site_assignments for select to anon
using (status <> 'cancelled');

create policy "Authenticated read assignments"
on public.site_assignments for select to authenticated
using (public.is_schedule_manager());

create policy "Public read assignment teams"
on public.assignment_teams for select to anon
using (true);

create policy "Authenticated read assignment teams"
on public.assignment_teams for select to authenticated
using (public.is_schedule_manager());

create policy "Public read assignment volunteers"
on public.assignment_volunteers for select to anon
using (true);

create policy "Authenticated read assignment volunteers"
on public.assignment_volunteers for select to authenticated
using (public.is_schedule_manager());

-- Team membership is private.
create policy "Managers read team members"
on public.project_team_members for select to authenticated
using (public.is_schedule_manager());

-- Admin profile: signed-in user can see only their own permission record.
create policy "Admin reads own profile"
on public.admin_profiles for select to authenticated
using (id = auth.uid());

-- Manager write policies.
create policy "Managers change volunteers"
on public.volunteers for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change teams"
on public.project_teams for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change team members"
on public.project_team_members for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change sites"
on public.survey_sites for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change rounds"
on public.survey_rounds for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change round sites"
on public.survey_round_sites for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change assignments"
on public.site_assignments for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change assignment teams"
on public.assignment_teams for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

create policy "Managers change assignment volunteers"
on public.assignment_volunteers for all to authenticated
using (public.is_schedule_manager())
with check (public.is_schedule_manager());

-- ============================================================
-- AFTER RUNNING THIS FILE:
-- Enable your existing Supabase Auth account as the manager:
--
-- update public.admin_profiles
-- set can_manage = true
-- where id = (
--   select id from auth.users where email = 'YOUR EMAIL ADDRESS'
-- );
--
-- Replace YOUR EMAIL ADDRESS before running that small query.
-- ============================================================
