-- Canal Watch Survey Schedule — Supabase schema
-- All users are volunteers.
-- Team coordination is a property of each project team, not a user role.

create type public.assignment_status as enum ('needed','covered','complete','cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.project_teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  coordinator_id uuid not null references public.profiles(id),
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now()
);

create table public.project_team_members (
  team_id bigint not null references public.project_teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  primary key (team_id,user_id)
);

create table public.survey_sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  address text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  three_word_location text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (
    (latitude is null and longitude is null)
    or
    (latitude is not null and longitude is not null)
  )
);

create table public.survey_rounds (
  id bigint generated by default as identity primary key,
  name text not null,
  survey_date date not null,
  status text not null default 'planned',
  recurrence text not null default 'none'
    check (recurrence in ('none','weekly','fortnightly','monthly','custom_days')),
  recurrence_interval integer not null default 1 check (recurrence_interval >= 1),
  auto_repeat boolean not null default false,
  parent_round_id bigint references public.survey_rounds(id),
  created_at timestamptz not null default now()
);


create table public.survey_round_sites (
  survey_round_id bigint not null references public.survey_rounds(id) on delete cascade,
  survey_site_id bigint not null references public.survey_sites(id),
  primary key (survey_round_id, survey_site_id)
);

create table public.site_assignments (
  id bigint generated by default as identity primary key,
  survey_round_id bigint not null references public.survey_rounds(id) on delete cascade,
  survey_site_id bigint not null references public.survey_sites(id),
  status public.assignment_status not null default 'needed',
  notes text,
  unique (survey_round_id, survey_site_id)
);

create table public.assignment_teams (
  assignment_id bigint not null references public.site_assignments(id) on delete cascade,
  team_id bigint not null references public.project_teams(id),
  primary key (assignment_id,team_id)
);

create table public.assignment_users (
  assignment_id bigint not null references public.site_assignments(id) on delete cascade,
  user_id uuid not null references public.profiles(id),
  primary key (assignment_id,user_id)
);

-- Recommended rule:
-- when a coordinator is selected for a project team, make sure that volunteer
-- is also included in project_team_members for that team.

-- Production security should use Supabase Auth + Row Level Security.
-- Public visitors should see schedule/coverage data only.
-- Personal contact details should remain available only to authenticated administrators.


-- Production recommendation:
-- Use a scheduled Supabase Edge Function / cron job to create the next
-- occurrence for rows where auto_repeat=true and survey_date has passed.
-- This is more reliable than relying on a browser session to generate it.


-- Volunteer email/contact detail is optional at application level.
-- If a separate volunteer contact table is added later, its email field should allow NULL.
